version: "3"
services:
  backend:
    restart: always
    container_name: backend
    build: ./backend
    expose:
      - 5000

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt/live/classes.gg:/etc/nginx/certs