version: "3"
services:
  backend:
    restart: always
    container_name: backend
    build: ./backend
    expose:
      - 5000
    volumes:
      - /root/classes.gg/backend/db:/database

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt/:/etc/nginx/certs