from enum import Enum


class Attachment(Enum):

    def __init__(self, name, aliases: list = None):
        self._name = name
        self._aliases = aliases if aliases else []

    def __str__(self):
        return self._name

    @property
    def aliases(self) -> list:
        return [self._name.lower()] + self._aliases

    @classmethod
    def get_class_name(cls):
        _type = cls.__name__
        if _type == RearGrip.__name__:
            return "Rear Grip"
        if _type == BoltAssembly.__name__:
            return "Bolt Assembly"
        return _type


class Ammunition(Attachment):
    AE_32_ROUND_MAGS_41 = ".41 AE 32-Round Mags"
    AUTO_30_ROUND_MAGS_10MM = "10mm Auto 30-Round Mags"
    BAKELITE_RND_40 = "Bakelite 40 Rnd"
    BAKELITE_RND_60 = "Bakelite 60 Rnd"
    BLACKOUT_30_ROUND_MAGS_300 = ".300 Blackout 30-Round Mags"
    CT_100_ROUND_BELTS_556 = "5.56 CT 100-Round Belts"
    CT_75_ROUND_BELTS_556 = "5.56 CT 75-Round Belts"
    EXPLOSIVE_5_R_MAGS_25X59MM = "25x59mm Explosive 5-R Mags"
    FAST_MAG = "Fast Mag"
    GRU_MAG_CLAMP = "GRU Mag Clamp"
    HOLLOW_POINT_12_R_MAGS_45 = ".45 Hollow Point 12-R Mags"
    JUNGLE_STYLE_MAG = "Jungle-Style Mag"
    LAPUA_MAG_338 = ".338 Lapua Mag 5-R Mags"
    M67_10_R_MAGS = "M67 10-R Mags"
    NATO_100_ROUND_BELTS_556 = "5.56 NATO 100-Round Belts"
    NATO_30_ROUND_MAGS_556 = "5.56 NATO 30-Round Mags"
    NATO_60_ROUND_DRUMS_556 = "5.56 NATO 60-Round Drums"
    NORMA_MAG_300 = ".300 Norma Mag 5-R Mags"
    PARA_32_ROUND_MAGS_9MM = "9mm Para 32-Round Mags"
    RND_100 = "100 Rnd"
    RND_120 = "120 Rnd"
    RND_30 = "30 Rnd"
    RND_38 = "38 Rnd"
    RND_40 = "40 Rnd"
    RND_42 = "42 Rnd"
    RND_45 = "45 Rnd"
    RND_65 = "65 Rnd"
    RND_DRUM_40 = "40 Rnd Drum"
    RND_DRUM_43 = "43 Rnd Drum"
    RND_DRUM_45 = "45 Rnd Drum"
    RND_SPEED_MAG_100 = "100 Rnd Speed Mag"
    RND_SPEED_MAG_120 = "120 Rnd Speed Mag"
    RND_SPEED_MAG_30 = "30 Rnd Speed Mag"
    RND_SPEED_MAG_38 = "38 Rnd Speed Mag"
    RND_SPEED_MAG_40 = "40 Rnd Speed Mag"
    RND_SPEED_MAG_42 = "42 Rnd Speed Mag"
    RND_SPEED_MAG_43 = "43 Rnd Speed Mag"
    RND_SPEED_MAG_45 = "45 Rnd Speed Mag"
    RND_SPEED_MAG_65 = "65 Rnd Speed Mag"
    ROUND_BELT_100 = "100 Round Belt"
    ROUND_BELT_120 = "120 Round Belt"
    ROUND_BELT_150 = "150 Round Belt"
    ROUND_BELT_200 = "200 Round Belt"
    ROUND_BELT_75 = "75 Round Belt"
    ROUND_CASKET_MAGS_60 = "60 Round Casket Mags"
    ROUND_DRUMS_100 = "100 Round Drums"
    ROUND_DRUMS_50 = "50 Round Drums"
    ROUND_DRUMS_80 = "80 Round Drums"
    ROUND_DRUM_MAGS_40 = "40 Round Drum Mags"
    ROUND_DRUM_MAGS_75 = "75 Round Drum Mags"
    ROUND_HELICAL_MAGS_84 = "84 Round Helical Mags"
    ROUND_MAGS_10 = "10 Round Mags", ["10 rnd", "10 rd"]
    ROUND_MAGS_15 = "15 Round Mags", ["15 rnd", "15 rd"]
    ROUND_MAGS_20 = "20 Round Mags", ["20 rnd", "20 rd"]
    ROUND_MAGS_24 = "24 Round Mags", ["24 rnd", "24 rd"]
    ROUND_MAGS_25 = "25 Round Mags", ["25 rnd", "25 rd"]
    ROUND_MAGS_30 = "30 Round Mags", ["30 rnd", "30 rd", "30 mag", "30 mags"]
    ROUND_MAGS_32 = "32 Round Mags", ["32 rnd", "32 rd"]
    ROUND_MAGS_40 = "40 Round Mags", ["40 rnd", "40 rd"]
    ROUND_MAGS_45 = "45 Round Mags", ["45 rnd", "45 rd", "45 rounds"]
    ROUND_MAGS_50 = "50 Round Mags", ["50 rnd", "50 rd", "50 mag", "50 mags"]
    ROUND_MAGS_60 = "60 Round Mags", ["60 rnd", "60 rd", "60 mag", "60 mags"]
    ROUND_MAGS_7 = "7 Round Mags", ["7 rnd", "7 rd"]
    ROUND_MAGS_9 = "9 Round Mags", ["9 rnd", "9 rd"]
    ROUND_MAG_10 = "10 Round Mag"
    ROUND_MAG_50 = "50 Round Mag"
    ROUND_MAG_60 = "60 Round Mag"
    ROUND_MAGS_545X39MM_30 = "5.45x39mm 30-Round Mags"
    SALVO_125_RND_FAST_MAG = "Salvo 125 Rnd Fast Mag"
    SALVO_150_RND_FAST_MAG = "Salvo 150 Rnd Fast Mag"
    SALVO_40_RND_FAST_MAG = "Salvo 40 Rnd Fast Mag"
    SALVO_48_RND_FAST_MAG = "Salvo 48 Rnd Fast Mag"
    SALVO_50_RND_FAST_MAG = "Salvo 50 Rnd Fast Mag"
    SALVO_52_RND_FAST_MAG = "Salvo 52 Rnd Fast Mag"
    SALVO_53_RND_FAST_MAG = "Salvo 53 Rnd Fast Mag"
    SALVO_54_RND_FAST_MAG = "Salvo 54 Rnd Fast Mag"
    SALVO_55_RND_FAST_MAG = "Salvo 55 Rnd Fast Mag"
    SALVO_60_RND_FAST_MAG = "Salvo 60 Rnd Fast Mag"
    SAS_MAG_CLAMP = "SAS Mag Clamp"
    SOCOM_10_ROUND_MAGS_458 = ".458 SOCOM 10-Round Mags"
    SPETSNAZ_125_RND = "Spetsnaz 125 Rnd"
    SPETSNAZ_150_RND = "Spetsnaz 150 Rnd"
    SPETSNAZ_50_RND = "Spetsnaz 50 Rnd"
    SPETSNAZ_50_RND_DRUM = "Spetsnaz 50 Rnd Drum"
    SPETSNAZ_60_RND_DRUM = "Spetsnaz 60 Rnd Drum"
    SPP_10_R_MAGS = "SPP 10-R Mags"
    STANAG_125_RND = "STANAG 125 Rnd"
    STANAG_40_RND = "STANAG 40 Rnd"
    STANAG_48_RND = "STANAG 48 Rnd"
    STANAG_50_RND = "STANAG 50 Rnd"
    STANAG_50_RND_DRUM = "STANAG 50 Rnd Drum", ["50 drum mag"]
    STANAG_53_RND_DRUM = "STANAG 53 Rnd Drum", ["53 drum mag"]
    STANAG_54_RND_DRUM = "STANAG 54 Rnd Drum", ["54 drum mag"]
    STANAG_55_RND_DRUM = "STANAG 55 Rnd Drum", ["55 drum mag"]
    STANAG_55_RND = "STANAG 55 Rnd"
    STANAG_60_RND = "STANAG 60 Rnd"
    STANAG_85_RND = "Stanag 85 Rnd"
    TAPED_MAGS = "Taped Mags"
    THERMITE_5_R_MAGS_25X59MM = "25x59mm Thermite 5-R Mags"
    VANDAL_SPEED_LOADER = "Vandal Speed Loader"
    VDV_125_RND_FAST_MAG = "VDV 125 Rnd Fast Mag"
    VDV_50_RND_FAST_MAG = "VDV 50 Rnd Fast Mag"
    VDV_60_RND_FAST_MAG = "VDV 60 Rnd Fast Mag"
    VDV_85_RND_FAST_MAG = "VDV 85 Rnd Fast Mag"


class Barrel(Attachment):
    ALUMINUM_87 = "8.7 Aluminum"
    AN_94_FACTORY_330MM = "AN-94 Factory 330mm"
    AN_94_FACTORY_X_438MM = "AN-94 Factory X-438mm", ["438 barrel"]
    BRUEN_180_PARA = "Bruen 18.0 Para"
    BULL_BARREL_172 = "17.2 Bull Barrel"
    BULL_BARREL_26 = "26 Bull Barrel"
    CAVALRY = "Cavalry"
    CAVALRY_101 = "10.1 Cavalry"
    CAVALRY_LANCER = "Cavalry Lancer"
    CMV_MIL_SPEC = "CMV Mil-Spec"
    COMPACT_BARREL_182 = "18.2 Compact Barrel"
    COMPACT_BARREL_510MM = "510mm Compact Barrel"
    COMPACT_BARREL_81 = "8.1 Compact Barrel"
    CONTOUR = "Contour"
    CONTOUR_M2 = "Contour M2"
    CORVUS_CUSTOM_MARKSMAN = "Corvus Custom Marksman"
    CUT_DOWN = "Cut Down"
    DIVISION = "Division"
    EXTENDED = "Extended"
    EXTENDED_407MM = "407mm Extended"
    EXTENDED_95 = "9.5 Extended"
    EXTENDED_BARREL_269 = "26.9 Extended Barrel"
    EXTENDED_BARREL_660MM = "660mm Extended Barrel"
    FACTORY_ADVERSE = "Factory Adverse"
    FACTORY_BARREL_17 = "17 Factory Barrel"
    FACTORY_BARREL_32 = "32 Factory Barrel"
    FACTORY_CARBINE_165 = "16.5 Factory Carbine"
    FACTORY_MINI_85 = "8.5 Factory Mini"
    FFS_208_NEXUS = "FFS 20.8 Nexus"
    FIRST_RESPONDER_131 = "13.1 First Responder"
    FORGE_TAC_172_LB = "Forge Tac 17.2 LB"
    FORGE_TAC_200_LB = "Forge Tac 20.0 LB"
    FORGE_TAC_CQC_PRO = "Forge Tac CQC Pro"
    FORGE_TAC_ECLIPSE = "Forge Tac Eclipse"
    FORGE_TAC_ELITE = "FORGE TAC Elite"
    FORGE_TAC_PRECISION_200 = "FORGE TAC Precision 20.0"
    FORGE_TAC_PRECISION_220 = "FORGE TAC Precision 22.0"
    FORGE_TAC_RETRIBUTION = "Forge Tac Retribution"
    FORGE_TAC_ULTRALIGHT = "FORGE TAC Ultralight"
    FR_159_COMMANDO = "FR 15.9 Commando"
    FR_244_SNIPER = "FR 24.4 Sniper"
    FSS_106_PRO = "FSS 10.6 Pro"
    FSS_115_COMMANDO = "FSS 11.5 Commando"
    FSS_118_SQUALL = "FSS 11.8 Squall"
    FSS_124_PREDATOR = "FSS 12.4 Predator"
    FSS_145_TAC_LITE = "FSS 14.5 Tac Lite"
    FSS_180_FACTORY = "FSS 18.0 Factory"
    FSS_200_FACTORY = "FSS 20.0 Factory"
    FSS_240_FACTORY = "FSS 24.0 Factory"
    FSS_83_INTRUDER = "FSS 8.3 Intruder"
    FSS_BRUTE = "FSS Brute"
    FSS_CARBINE_PRO = "FSS Carbine Pro"
    FSS_ELITE = "FSS Elite"
    FSS_LIGHT = "FSS Light"
    FSS_M59_66_22 = "22 FSS M59/66"
    FSS_MINI = "FSS Mini"
    FSS_NIGHTSHADE = "FSS Nightshade"
    FSS_PARA_16 = "16 FSS Para"
    FSS_RANGER = "FSS Ranger"
    FSS_RECON = "FSS RECON"
    FSS_REVOLUTION = "FSS Revolution"
    FSS_STRIKE = "FSS STRIKE"
    FSS_STUBBY = "FSS Stubby"
    FSS_SWAT = "FSS SWAT"
    FTAC_135_COMPACT = "FTAC 13.5 Compact"
    FTAC_225_DOMINATOR = "FTAC 225 Dominator"
    FTAC_448MM_DICTATOR = "FTAC 448mm Dictator"
    FTAC_898_SPITFIRE = "FTAC 8.98 Spitfire"
    FTAC_LANDMARK = "FTAC Landmark"
    FTAC_SEVEN_STRAIGHT = "FTAC Seven Straight"
    FTAC_VC_8_HARRIER = "FTAC VC-8 Harrier"
    FTAC_VC_8_HARRIER_ADVERSE = "FTAC VC-8 Harrier Adverse"
    GRU_COMPOSITE = "GRU Composite"
    GRU_CUT_DOWN = "GRU Cut Down"
    HDR_PRO_269 = "26.9 HDR Pro"
    HEAVY_BARREL_259 = "25.9 Heavy Barrel", ["25.9 barrel"]
    ISO_140MM_CQB = "ISO 140mm CQB"
    LIBERATOR = "Liberator"
    LIGHTWEIGHT_407MM = "407mm Lightweight"
    LONG_BARREL_622MM = "622mm Long Barrel"
    M91_HEAVY = "M91 Heavy"
    M91_INFANTRY = "M91 Infantry"
    M91_SPECIAL_FORCES = "M91 Special Forces"
    MATCH_GRADE = "Match Grade"
    MONOLITHIC_INTEGRAL_SUPPRESSOR = "Monolithic Integral Suppressor"
    ODEN_FACTORY_420MM = "Oden Factory 420mm"
    ODEN_FACTORY_730MM = "Oden Factory 730mm"
    ODEN_FACTORY_810MM = "Oden Factory 810mm", ["810mm"]
    OSW_PARA_130 = "13.0 OSW Para"
    POLYGONAL_87 = "8.7 Polygonal"
    POLY_BARREL_300MM = "300mm Poly Barrel"
    RANGER = "Ranger"
    RANGER_95 = "9.5 Ranger"
    RAPID_FIRE = "Rapid Fire"
    REINFORCED_HEAVY = "Reinforced Heavy"
    REINFORCED_HEAVY_95 = "9.5 Reinforced Heavy"
    RIFLED = "Rifled"
    RIFLED_91 = "9.1 Rifled"
    ROMANIAN_230 = "23.0 Romanian"
    RPK_BARREL_230 = "23.0 RPK Barrel"
    SA87_124_FACTORY = "SA87 12.4 Factory"
    SA87_182_FACTORY = "SA87 18.2 Factory"
    SA87_254_FACTORY = "SA87 25.4 Factory"
    SINGUARD_ARMS_166_SOCOM = "Singuard Arms 16.6 SOCOM"
    SINGUARD_ARMS_198_PROWLER = "Singuard Arms 19.8 Prowler", ["singuard 19.8", "prowler"]
    SINGUARD_ARMS_PRO = "Singuard Arms Pro"
    SINGUARD_ARMS_WHISPER = "Singuard Arms Whisper"
    SINGUARD_CUSTOM_212 = "Singuard Custom 21.2"
    SINGUARD_CUSTOM_251 = "Singuard Custom 25.1"
    SINGUARD_CUSTOM_276 = "Singuard Custom 27.6", ["singuard 27.6"]
    SOROKIN_140MM_AUTO = "Sorokin 140mm Auto"
    SOR_CUT_DOWN = "SOR Cut Down"
    SPETSNAZ_ELITE = "Spetsnaz Elite"
    SPETSNAZ_RPK = "Spetsnaz RPK"
    SPETSNAZ_RPK_BARREL = "Spetsnaz RPK Barrel"
    SP_R_26 = "SP-R 26"
    STAINLESS_STEEL_150MM = "150mm Stainless Steel"
    STAINLESS_STEEL_400MM = "400mm Stainless Steel"
    STEEL_87 = "8.7 Steel"
    STOCK_M16_GRENADIER = "Stock M16 Grenadier", ["m16 grenadier"]
    STOVL_SOF = "Stovl SOF"
    STRIKE_TEAM = "Strike Team"
    SUBSONIC_INTEGRAL_SUPPRESSOR = "Subsonic Integral Suppressor"
    TAKEDOWN = "Takedown"
    TASK_FORCE = "Task Force"
    TASK_FORCE_95 = "9.5 Task Force", ["task force"]
    TEMPUS_264_ARCHANGEL = "Tempus 26.4 Archangel", ["archangel"]
    TEMPUS_CYCLONE = "Tempus Cyclone"
    TEMPUS_MARKSMAN = "Tempus Marksman"
    TEMPUS_MINI = "Tempus Mini"
    TITANIUM = "Titanium"
    ULTRALIGHT = "Ultralight"
    ULTRALIGHT_180 = "18.0 Ultralight"
    VDV_REINFORCED = "VDV Reinforced"
    VLK_105MM_STOVA = "VLK 105mm Stova"
    VLK_200MM_OSA = "VLK 200mm Osa"
    VLK_AN_94_SILA = "VLK AN-94 Sila"
    XRK_208_DRAGOON = "XRK 208 Dragoon"
    XRK_CZEN_MK2 = "XRK CZEN mk2"
    XRK_HARBINGER = "XRK Harbinger"
    XRK_HORIZON_230 = "XRK Horizon 23.0"
    XRK_LONGSHOT_ADVANTAGE = "XRK LongShot Advantage"
    XRK_LONGSHOT_ADVERSE = "XRK LongShot Adverse"
    XRK_MARKSMAN = "XRK Marksman"
    XRK_PRO_TWIST = "XRK Pro Twist"
    XRK_PRO_TWIST_ADVERSE = "XRK Pro Twist Adverse"
    XRK_SUMMIT_268 = "XRK Summit 26.8", ["summit"]
    XRK_ULTRALIGHT = "XRK Ultralight"
    XRK_ZODIAC_S440 = "XRK Zodiac S440"
    ZLR_16_APEX = "ZLR 16 Apex"
    ZLR_18_DEADFALL = "ZLR 18 Deadfall"
    ZLR_ASP = "ZLR Asp"
    ZLR_DRIFTER_A08 = "ZLR Drifter A08"
    ZLR_VERATWIST_96 = "ZLR VeraTwist 9.6"


class Laser(Attachment):
    EMBER_SIGHTING_POINT = "Ember Sighting Point"
    GRU_5MW_LASER_SIGHT = "GRU 5mW Laser Sight"
    KGB_TARGET_DESIGNATOR = "KGB Target Designator"
    LASER_1MW = "1mW Laser"
    LASER_5MW = "5mW Laser"
    MOUNTED_FLASHLIGHT = "Mounted Flashlight"
    SOF_TARGET_DESIGNATOR = "SOF Target Designator"
    STEADY_AIM_LASER = "Steady Aim Laser"
    SWAT_5MW_LASER_SIGHT = "SWAT 5mW Laser Sight"
    TAC_LASER = "Tac Laser"
    TIGER_TEAM_SPOTLIGHT = "Tiger Team Spotlight"


class Muzzle(Attachment):
    AGENCY_SUPPRESSOR = "Agency Suppressor", ["agency silencer"]
    AN_94_SONIC_BRAKE = "AN-94 Sonic Brake"
    BAYONET = "BAYONET"
    COLOSSUS_SUPPRESSOR = "Colossus Suppressor"
    COMPENSATOR = "Compensator"
    CQB_BREACHER_DEVICE = "CQB Breacher Device"
    FLASH_GUARD = "Flash Guard"
    GRU_SILENCER = "GRU Silencer"
    GRU_SUPPRESSOR = "GRU Suppressor"
    INFANTRY_COMPENSATOR = "Infantry Compensator"
    KGB_ELIMINATOR = "KGB Eliminator"
    LIGHTWEIGHT_SUPPRESSOR = "Lightweight Suppressor"
    MONOLITHIC_SUPPRESSOR = "Monolithic Suppressor", ["mono", "monolithic"]
    MUZZLE_BRAKE = "Muzzle Brake"
    RYTEC_AMR_SUPPRESSOR = "Rytec AMR Suppressor"
    SILENCER = "Silencer"
    SOCOM_ELIMINATOR = "SOCOM Eliminator"
    SOUND_SUPPRESSOR = "Sound Suppressor"
    SPETSNAZ_COMPENSATOR = "Spetsnaz Compensator"
    SUPPRESSOR = "Suppressor"
    TACTICAL_SUPPRESSOR = "Tactical Suppressor"
    XRK_TANK_BRAKE = "XRK Tank Brake"
    ZLR_SABRE = "ZLR Sabre"


class Optic(Attachment):
    AIM_OP_REFLEX_SIGHT = "Aim-Op Reflex Sight"
    ANPVS_4_THERMAL = "AN/PVS-4 Thermal"
    APX5_HOLOGRAPHIC = "APX5 Holographic", ["apx5 holo"]
    APX5_HOLOGRAPHIC_SIGHT = "APX5 Holographic Sight", ["apx5 holo"]
    AXIAL_ARMS_3X = "Axial Arms 3x"
    CANTED_HYBRID = "Canted Hybrid"
    CORP_COMBAT_HOLO_SIGHT = "Corp Combat Holo Sight", ["corp combat"]
    CRONEN_2X2_ELITE = "Cronen 2x2 Elite"
    CRONEN_C480_PRO_OPTIC = "Cronen C480 Pro Optic"
    CRONEN_LP945_MINI_REFLEX = "Cronen LP945 Mini Reflex"
    DIAMONDBACK_REFLEX = "Diamondback Reflex"
    DRAGUNOV_SCOPE = "Dragunov Scope"
    FASTPOINT_REFLEX = "Fastpoint Reflex"
    FLIP_HYBRID_40X = "4.0x Flip Hybrid"
    FSS_INTEGRAL_REFLEX = "FSS Integral Reflex"
    FSS_RING_SIGHT = "FSS Ring Sight"
    GI_MINI_REFLEX = "G.I. Mini Reflex"
    HANGMAN_RF = "Hangman RF"
    HAWKSMOOR = "Hawksmoor"
    INTEGRAL_30X_OPTIC = "Integral 3.0x Optic"
    INTEGRAL_HYBRID = "Integral Hybrid"
    KOBRA_RED_DOT = "Kobra Red Dot"
    MERC_THERMAL_OPTIC = "Merc Thermal Optic"
    MICROFLEX_LED = "Microflex LED"
    MILLSTOP_REFLEX = "Millstop Reflex"
    MONOCLE_REFLEX_SIGHT = "Monocle Reflex Sight"
    NOCH_SOVA_THERMAL = "Noch Sova Thermal"
    OPERATOR_REFLEX_SIGHT = "Operator Reflex Sight"
    PBX_HOLO_7_SIGHT = "PBX Holo 7 Sight"
    POS_M3_THERMAL_SCOPE = "POS-M3 Thermal Scope"
    PU_SCOPE = "PU Scope"
    QUICKDOT_LED = "Quickdot LED"
    ROYAL_AND_CROSS_4X = "Royal & Cross 4x"
    SCOUT_COMBAT_OPTIC = "Scout Combat Optic"
    SILLIX_HOLOSCOUT = "Sillix Holoscout"
    SNAPPOINT = "SnapPoint"
    SNIPER_SCOPE = "Sniper Scope"
    SOLOZERO_K498_40X_INTEGRAL = "Solozero K498 4.0x Integral"
    SOLOZERO_NVG_ENHANCED = "Solozero NVG Enhanced"
    SOLOZERO_OPTICS_MINI_REFLEX = "Solozero Optics Mini Reflex"
    SOLOZERO_SP_R_28MM = "Solozero SP-R 28mm"
    SUSAT_MULTIZOOM = "SUSAT Multizoom"
    THERMAL_DUAL_POWER_SCOPE = "Thermal Dual Power Scope"
    THERMAL_HYBRID = "Thermal Hybrid"
    THERMAL_SNIPER_SCOPE = "Thermal Sniper Scope"
    VARIABLE_ZOOM_SCOPE = "Variable Zoom Scope"
    VIPER_REFLEX_SIGHT = "Viper Reflex Sight"
    VISIONTECH_2X = "Visiontech 2x"
    VLK_30X_OPTIC = "VLK 3.0x Optic", ["vlk"]
    VULTURE_CUSTOM_ZOOM = "Vulture Custom Zoom"
    XRK_MIDTRAK_40X_SCOPE = "XRK MidTrak 4.0x Scope"
    XRK_RANGEMASTER_VZ = "XRK Rangemaster VZ"


class Perk(Attachment):
    AKIMBO = "Akimbo"
    FMJ = "FMJ"
    FOCUS = "Focus"
    FULLY_LOADED = "Fully Loaded"
    RECON = "Recon"
    SLEIGHT_OF_HAND = "Sleight of Hand"


class RearGrip(Attachment):
    AIRBORNE_ELASTIC_GRIP = "Airborne Elastic Grip"
    AIRBORNE_ELASTIC_WRAP = "Airborne Elastic Wrap"
    CRONEN_SNIPER_ELITE = "Cronen Sniper Elite"
    DROPSHOT_WRAP = "Dropshot Wrap"
    FIELD_TAPE = "Field Tape"
    FSS_VICE_ISO_GRIP = "FSS Vice ISO Grip"
    FTAC_ELITE_ISO_GRIP = "FTAC Elite ISO Grip"
    FTAC_G_5_EXO = "FTAC G-5 EXO"
    FTAC_RUBBER = "FTAC R-89 Rubber"
    GRANULATED_GRIP_TAPE = "Granulated Grip Tape"
    GRU_ELASTIC_WRAP = "GRU Elastic Wrap"
    ISO_TAC_FORM = "ISO Tac-Form"
    RUBBERIZED_GRIP_TAPE = "Rubberized Grip Tape"
    SASR_JUNGLE_GRIP = "SASR Jungle Grip"
    SERPENT_GRIP = "Serpent Grip"
    SERPENT_WRAP = "Serpent Wrap"
    SPEED_TAPE = "Speed Tape"
    SPETSNAZ_FIELD_GRIP = "Spetsnaz Field Grip"
    STIPPLED_GRIP_TAPE = "Stippled Grip Tape", ["stippled rear grip"]
    VLK_PRIZRAK = "VLK Prizrak", ["prizrak"]
    XRK_CR_56_GRANULATED_WRAP = "XRK CR-56 Granulated Wrap", ["granulated"]
    XRK_CR_56_RUBBERIZED_WRAP = "XRK CR-56 Rubberized Wrap", ["rubberized"]
    XRK_CR_56_STIPPLED_WRAP = "XRK CR-56 Stippled Wrap", ["stippled"]
    XRK_VOID_II = "XRK Void II"


class Stock(Attachment):
    AN_94_FACTORY_HEAVY = "AN-94 Factory Heavy"
    BUFFER_TUBE = "Buffer Tube"
    CARTRIDGE_SLEEVE = "Cartridge Sleeve"
    CLASSIC_STRAIGHT_LINE_STOCK = "Classic Straight-line Stock"
    COLLAPSED_STOCK = "Collapsed Stock"
    CORVUS_SKELETON_STOCK = "Corvus Skeleton Stock"
    CQB_PAD = "CQB Pad"
    CR_56_EXO = "CR-56 EXO"
    DUSTER_PAD = "Duster Pad"
    DUSTER_STOCK = "Duster Stock"
    FACTORY_18_ALUMINUM_STOCK = "Factory 18 Aluminum Stock"
    FACTORY_ALUMINUM_STOCK = "Factory Aluminum Stock"
    FIELD_LMG_STOCK = "Field LMG Stock"
    FLY_STRAP = "Fly Strap"
    FOLDED_STOCK = "Folded Stock"
    FORGE_TAC_APEX = "FORGE TAC Apex"
    FORGE_TAC_BALLAST_PACK = "FORGE TAC Ballast Pack"
    FORGE_TAC_CQB_COMB = "FORGE TAC CQB Comb"
    FORGE_TAC_CQS = "FORGE TAC CQS"
    FORGE_TAC_DART_CB = "FORGE TAC Dart CB"
    FORGE_TAC_SPEEDTRAK = "FORGE TAC SpeedTrak"
    FORGE_TAC_STALKER = "FORGE TAC Stalker"
    FORGE_TAC_ULTRALIGHT = "FORGE TAC Ultralight"
    FR_ULTRALIGHT_HOLLOW = "FR Ultralight Hollow"
    FSS_BLACKJACK = "FSS Blackjack"
    FSS_CLOSE_QUARTERS_STOCK = "FSS Close Quarters Stock"
    FSS_GUARDIAN = "FSS Guardian"
    FSS_HEAVY_STOCK_PRO = "FSS Heavy Stock Pro"
    FSS_INFANTRY = "FSS Infantry"
    FSS_INTL_GEN_4_GRU = "FSS Intl. Gen 4 GRU"
    FSS_MK2_PRECISION_COMB = "FSS MK2 Precision Comb"
    FSS_MK2_SPORT_COMB = "FSS MK2 Sport Comb"
    FSS_NOMAD_STOCK = "FSS Nomad Stock"
    FSS_RAIDER_CHASSIS_ELITE = "FSS Raider Chassis Elite"
    FSS_RAIDER_CHASSIS_PRO = "FSS Raider Chassis Pro"
    FSS_RANGER = "FSS Ranger"
    FSS_TAC_WRAP = "FSS Tac-Wrap"
    FSS_VIRTUOSO_PRO = "FSS Virtuoso Pro"
    FTAC_C6_CARBINE_PRO = "FTAC C6 Carbine PRO"
    FTAC_CHAMPION = "FTAC Champion"
    FTAC_COLLAPSIBLE = "FTAC Collapsible"
    FTAC_COLLAPSIBLE_STOCK = "FTAC Collapsible Stock"
    FTAC_EQUILIBRIUM = "FTAC Equilibrium"
    FTAC_HUNTER = "FTAC Hunter"
    FTAC_HUNTER_SCOUT = "FTAC Hunter-Scout"
    FTAC_LIGHTWEIGHT_STOCK = "FTAC Lightweight Stock"
    FTAC_PRECISION_COMB = "FTAC Precision Comb"
    FTAC_PRECISION_FIXED_STOCK = "FTAC Precision Fixed Stock"
    FTAC_SPARTAN = "FTAC Spartan"
    FTAC_SPORT_COMB = "FTAC Sport Comb"
    FTAC_STALKER_SCOUT = "FTAC Stalker-Scout"
    FTAC_TREKKER = "FTAC Trekker"
    FTAC_ULTRALIGHT_HOLLOW = "FTAC Ultralight Hollow"
    FTAC_VAGRANT = "FTAC Vagrant"
    FTAC_XL_ELITE_COMB = "FTAC XL Elite Comb"
    HOLLOW_STOCK_MOD = "Hollow Stock Mod"
    ISO_COLLAPSIBLE = "ISO Collapsible"
    KGC_PAD = "KGB Pad"
    KGB_SKELETAL_STOCK = "KGB Skeletal Stock"
    M13_SKELETON_STOCK = "M13 Skeleton Stock"
    MARATHON_STOCK = "Marathon Stock"
    MK2_ULTRALIGHT_HOLLOW = "MK2 Ultralight Hollow"
    M_16_STOCK = "M-16 Stock"
    NO_STOCK = "No Stock"
    ODEN_ULTRALIGHT_HOLLOW = "Oden Ultralight Hollow"
    RAIDER_PAD = "Raider Pad"
    RAIDER_STOCK = "Raider Stock"
    SA87_ULTRALIGHT_HOLLOW = "SA87 Ultralight Hollow"
    SAS_COMBAT_STOCK = "SAS Combat Stock", ["sas stock"]
    SAWED_OFF_STOCK = "Sawed-off Stock"
    SINGUARD_ARMS_ASSASSIN = "Singuard Arms Assassin"
    SINGUARD_ARMS_EVADER = "Singuard Arms Evader"
    SINGUARD_ARMS_INVADER = "Singuard Arms Invader"
    SINGUARD_ARMS_MARKSMAN = "Singuard Arms Marksman"
    SINGUARD_ARMS_SNIPER_PRO = "Singuard Arms Sniper Pro"
    SKELETON_STOCK = "Skeleton Stock"
    SKS_RIFLE_STOCK = "SKS Rifle Stock"
    SPETSNAZ_PKM_STOCK = "Spetsnaz PKM Stock"
    STANDARD_ISSUE_WOOD_STOCK = "Standard-Issue Wood Stock"
    STOVL_6P30_SKELET = "Stovl 6P30 Skelet"
    STOVL_TAC_WRAP = "STOVL Tac-Wrap"
    STVOL_PRECISION_COMB = "STVOL Precision Comb"
    TACTICAL_STOCK = "Tactical Stock"
    VLK_LIGHTWEIGHT_STOCK = "VLK Lightweight Stock"
    VLK_PX_9_PERO = "VLK PX-9 Pero"
    VLK_STRELOK = "VLK Strelok"
    VLK_VINTAZH = "VLK Vintazh"
    WIRE_STOCK = "Wire Stock"
    XRK_AXIS = "XRK Axis"
    XRK_CHAINSAW = "XRK ChainSAW"
    XRK_CITADEL = "XRK Citadel"
    XRK_CLOSE_QUARTERS_STOCK = "XRK Close Quarters Stock"
    XRK_GATEKEEPER = "XRK Gatekeeper"
    XRK_GEN_III_SURVIVALIST_SERIES = "XRK Gen III Survivalist Series"
    XRK_M309_FORWARD_ASSAULT = "XRK M309 Forward Assault"
    XRK_MASTADON = "XRK Mastadon"
    XRK_OBELISK_PRO = "XRK Obelisk Pro"
    XRK_SA87_HEAVY_STOCK_PRO = "XRK SA87 Heavy Stock Pro"
    XRK_SP_LITE_208_BLITZ = "XRK SP-LITE 208 Blitz"
    XRK_SP_TAC_208_ULTIMATE = "XRK SP-TAC 208 Ultimate"
    XRK_STRIKELITE_III = "XRK StrikeLite III"
    XRK_STRIKER = "XRK Striker"
    XRK_ULTRALIGHT_HOLLOW = "XRK Ultralight Hollow"
    ZLR_BLADE = "ZLR Blade"
    ZLR_SP_R_OVERSEER = "ZLR SP-R Overseer"


class Underbarrel(Attachment):
    BIPOD = "Bipod"
    BIPOD_FOREGRIP = "Bipod Foregrip"
    BRUISER_GRIP = "Bruiser Grip"
    COMMANDO_FOREGRIP = "Commando Foregrip", ["commando grip"]
    CRONEN_SHARK_II = "Cronen Shark II"
    FIELD_AGENT_FOREGRIP = "Field Agent Foregrip"
    FIELD_AGENT_GRIP = "Field Agent Grip"
    FOREGRIP = "Foregrip"
    FRONT_GRIP = "Front Grip"
    FTAC_SPEED_GRIP = "FTAC Speed Grip"
    GRANULATED_GRIP_TAPE = "Granulated Grip Tape"
    INFILTRATOR_GRIP = "Infiltrator Grip"
    MERC_FOREGRIP = "Merc Foregrip"
    OPERATOR_FOREGRIP = "Operator Foregrip"
    PATROL_GRIP = "Patrol Grip"
    RANGER_FOREGRIP = "Ranger Foregrip"
    RED_CELL_FOREGRIP = "Red Cell Foregrip"
    RUBBERIZED_GRIP_TAPE = "Rubberized Grip Tape"
    SFOD_SPEEDGRIP = "SFOD Speedgrip"
    SNATCH_GRIP = "Snatch Grip"
    SPETSNAZ_GRIP = "Spetsnaz Grip"
    SPETSNAZ_SPEEDGRIP = "Spetsnaz Speedgrip"
    STIPPLED_GRIP_TAPE = "Stippled Grip Tape", ["stippled grip underbarrel"]
    STRIKER_GRIP = "Striker Grip"
    TACTICAL_FOREGRIP = "Tactical Foregrip"
    VDV_SPEEDGRIP = "VDV Speedgrip"
    XRK_PRECISION_COMB = "XRK Precision Comb"
    XRK_TALON = "XRK Talon"


class Arms(Attachment):
    XRK_CARBON_ELITE = "XRK Carbon Elite"
    XRK_QUILL_100_LB = "XRK Quill 100 Lb"
    XRK_THUNDER_200_LB = "XRK Thunder 200 Lb"


class Bolt(Attachment):
    FTAC_BACKBURN_20_BOLTS = "FTAC Backburn 20 Bolts"
    FTAC_FURY_20_BOLTS = "FTAC Fury 20 Bolts"
    FTAC_VENOM_20_BOLTS = "FTAC Venom 20 Bolts"


class Cable(Attachment):
    STRAND_CABLE_16 = "16 Strand Cable"
    STRAND_CABLE_28 = "28 Strand Cable"


class BoltAssembly(Attachment):
    SLOAN_KR_600_FEATHER = "Sloan KR-600 Feather"
    SLOAN_KR_800_DEADEYE = "Sloan KR-800 DeadEye"
